<a href="https://colab.research.google.com/github/yashrith/Ml-Notes/blob/master/Manual-calc-concepts/manual_calc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manual Calculation of a perceptron

### x = 3 inputs[1,2,3]
### y= output of 2 neurons
### w = weight matrix between input and the first hidden layer
### v= weight matrix between the first hidden layer and output
### hidden layer has 4 neurons
### implement a mlp with one hidden layer
### how many hyper parameter we have in this network

In [1]:
import numpy as np

In [12]:
# input neurons
X=np.array([1,2,3])

In [4]:
# these are the weights between input and hidden layer
W = np.random.randn(3, 4)
W

array([[-1.05060095, -0.16106238, -0.87451567,  0.0241128 ],
       [-0.04756618,  0.11846952, -0.28034578,  1.24597794],
       [-0.51824724, -1.28804136, -0.4542416 , -2.03698035]])

In [6]:
# these are the weights between hidden layer and output
V=np.random.randn(4,2)
V

array([[ 0.3907549 , -0.92073158],
       [ 1.13530267,  1.65493837],
       [ 0.33213383,  1.5212699 ],
       [ 1.39973846, -1.86599367]])

In [9]:
# biases for 4 neurons (1 hidden layer)
hid_b=np.random.randn(4)
hid_b

array([-0.36591506, -0.98566998, -0.60585798, -0.35378892])

In [10]:
# biases for 2 neurons (output layer)
out_b=np.random.randn(2)
out_b

array([0.3877826 , 0.64407887])

In [21]:
# Activation function
def relu(x):
  return np.maximum(0, x)

In [13]:
# input to hidden layer
# X * W + hid_b
in_to_hl=np.dot(X,W) + hid_b
in_to_hl

array([-3.0663901 , -4.77391741, -3.40379002, -3.94866128])

In [24]:
# now apply activation function
fh=relu(in_to_hl)
fh

array([0., 0., 0., 0.])

In [25]:
# now fh to output
# fh * V + out_b
fo=np.dot(fh,V) + out_b
fo

array([0.3877826 , 0.64407887])

In [26]:
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

In [28]:
final_out=leaky_relu(fo)
final_out

array([0.3877826 , 0.64407887])